#!/bin/bash
# ===================================================================#
# Copyright (c) 2022 Guilherme Esmeraldo - License GPLv3+:           #
# GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.    #
# This is free software: you are free to change and redistribute it. # 
# There is NO WARRANTY, to the extent permitted by law.              #
#                                                                    #
# Version: 0.2                                                       #
#====================================================================#


PIS_DIR="/var/log/PIS"
DIALOG_OK=0
DIALOG_CANCEL=1
DIALOG_ESC=255

opcao=$( dialog  --stdout \
--backtitle "Slackware Post-Install Scripts v0.2" \
--title "Set Login Mode" \
--menu  "Select login mode:" \
0 0 0 \
"CLI" "Command Line Interface" \
"GUI" "Graphical User Interface" )

if [ $? -eq 0 ]; then
	case $opcao in
		"CLI")
		#	echo "CLI"
			sed -i "s/id:.:initdefault:/id:3:initdefault:/" /etc/inittab

            echo "$opcao" > "$PIS_DIR/login"

			dialog --backtitle "Slackware Post-Install Scripts v0.2" --msgbox "Login mode has been setted to 'CLI'!" 5 40
			;;
		"GUI")
		#	echo "GUI"
			sed -i "s/id:.:initdefault:/id:4:initdefault:/" /etc/inittab

            echo "$opcao" > "$PIS_DIR/login"

			dialog --backtitle "Slackware Post-Install Scripts v0.2" --msgbox "Login mode has been setted to 'GUI'!" 5 40 
			;;
	esac
fi
