#!/bin/bash
# ===================================================================#
# Copyright (c) 2022 Guilherme Esmeraldo - License GPLv3+:           #
# GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.    #
# This is free software: you are free to change and redistribute it. # 
# There is NO WARRANTY, to the extent permitted by law.              #
#                                                                    #
# Version: 0.2                                                       #
#====================================================================#

PIS_DIR="/var/log/PIS"

wget https://www.jaos.org/slackpacks/slackware64-14.2/gslapt/gslapt-0.5.9-x86_64-2.txz -P /tmp
installpkg /tmp/gslapt-0.5.9-x86_64-2.txz

echo "YES" > "$PIS_DIR/slapt_get_gslapt"

dialog --backtitle "Slackware Post-Install Scripts v0.2" --msgbox "Gslapt is ready for packages management!" 5 45

